FROM python:3.9-slim

# Set a working directory
WORKDIR /app

# Copy the requirements file
COPY ../requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create a non-root user
RUN useradd -ms /bin/bash celeryuser

# Set the user to 'celeryuser'
USER celeryuser

# Copy the rest of the application code
COPY . /app

# Run Celery as non-root
ENTRYPOINT ["celery", "-A", "celery_config.celery_app", "worker", "--loglevel=info"]
