name: DataFeed CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for FastAPI
      uses: docker/build-push-action@v2
      with:
        context: ./fastapi
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi:latest

    - name: Build and push Docker image for Celery
      uses: docker/build-push-action@v2
      with:
        context: ./celery
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/celery:latest

    - name: Build and push Docker image for Celery Beat
      uses: docker/build-push-action@v2
      with:
        context: ./celery_beat
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/celery_beat:latest

    - name: Build and push Docker image for TimescaleDB
      uses: docker/build-push-action@v2
      with:
        context: ./timescaledb
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/timescaledb:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to the server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
        docker pull ${{ secrets.DOCKER_USERNAME }}/celery:latest
        docker pull ${{ secrets.DOCKER_USERNAME }}/celery_beat:latest
        docker pull ${{ secrets.DOCKER_USERNAME }}/timescaledb:latest

        docker-compose down
        docker-compose up -d
        EOF
