# name: Deploy FastAPI App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.3
#       with:
#         ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

#     - name: Install Docker Compose on VPS
#       run: |
#         ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
#         sudo apt-get update
#         sudo apt-get install -y docker-compose
#         EOF

#     - name: Copy Files to VPS
#       run: |
#         rsync -avz --exclude '__pycache__' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/app/

#     - name: Deploy FastAPI with Docker Compose
#       run: |
#         ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
#         cd /home/${{ secrets.VPS_USER }}/app/
#         docker-compose down
#         docker-compose up --build -d
#         EOF
